version: "3"
services:
  node-app:
    build:
      context: .
      args: 
        - NODE_ENV=development
    volumes:
      - .:/usr/src/app:ro
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
