version: '3'
services:
  node-app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./.env
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nimish
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db: